# server:
#   port: 8001
spring:
  application:
    name: 'API Crud Database NOSQL'
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
#  datasource:
#    url: jdbc:h2:file:/data/demo
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  sql:
    init:
      mode: always
